version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: tempsens-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: tempsens-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:5.7
    container_name: tempsens-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3307 on the container
      - '3307'
    # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
# Names our volume
volumes:
  mysql-data:
