version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: tempsens-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: tempsens-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  # PDO host will be "db"
  db:
    image: mysql:8.0
    container_name: tempsens-db
    restart: always
    environment:
      MYSQL_DATABASE: ${dbName}
      MYSQL_USER: ${dbUsername}
      MYSQL_PASSWORD: ${dbPassword}
      MYSQL_ROOT_PASSWORD: ${dbPassword}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      # PDO will use container port
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
    # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
# Names our volume
volumes:
  mysql-data:
